apiVersion: v1
kind: Service
metadata:
  name: chat-webserver-service
spec:
  selector:
    app: chat-webserver
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-webserver
spec:
  selector:
    matchLabels:
      app: chat-webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: chat-webserver
    spec:
      containers:
      - name: chat-webserver
        image: chat-webserver:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
